jdk:
- oraclejdk8
# would just use default install/script but the ./mvnw script errors on travis
# obviously this only works for maven builds right now...
install: true
script:
- mvn install
after_success:
  - mvn clean cobertura:cobertura coveralls:report
